[build]
publish = "public/"

[build.processing]
skip_processing = true

[functions]
directory = "build/remix/production/netlify/"

[[redirects]]
from = "/*"
to = "/.netlify/functions/index-bundle"
status = 200
force = false # serve static assets matching request paths without calling lambda

[[headers]]
for = "/build/*"
values = { cache-control = "max-age=31536000, immutable" }
