name: CI
"on":
  - push
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: "6.29.1"
      - uses: actions/setup-node@v2
        with:
          node-version: "16.14.0"
      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint

  tsc:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: "6.29.1"
      - uses: actions/setup-node@v2
        with:
          node-version: "16.14.0"
      - run: pnpm install --frozen-lockfile
      - run: pnpm run tsc

  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: "6.29.1"
      - uses: actions/setup-node@v2
        with:
          node-version: "16.14.0"
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build

  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: "6.29.1"
      - uses: actions/setup-node@v2
        with:
          node-version: "16.14.0"
      - run: pnpm install --frozen-lockfile
      - run: pnpm run services:up
      - run: pnpm run services:wait
      - run: pnpm run db:reset:test
      - run: pnpm run db:migrate:test
      - run: pnpm run test
